// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  controllSidebar: [{type: 'autogenerated', dirName: 'instruction'}],
  // aboutSidebar: [{type: 'autogenerated', dirName: 'about'}],
  // algorithmsSidebar: [{type: 'autogenerated', dirName: 'algorithms'}],
  // apiSidebar: [{type: 'autogenerated', dirName: 'API'}],
  // doxygenSidebar: [{type: 'autogenerated', dirName: 'doxygen'}],
};

export default sidebars;
